### ISSUE TITLE
POV export: missing texture: textures/powertower_vertical.orig.png

### ISSUE THREAD

**Issue by koppi** [tordanik/OSM2World#108]
``` bash
koppi@x220:~/Downloads/OSM2World$ unzip OSM2World-latest-bin.zip 
Archive:  OSM2World-latest-bin.zip
replace osm2world.sh? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: osm2world.sh            
  inflating: COPYING.txt             
  inflating: OSM2World.jar           
  inflating: example_config.properties  
  inflating: gpl.txt                 
  inflating: lgpl.txt                
  inflating: lib/commons/commons-math3-3.0.jar  
  inflating: lib/configuration/LICENSE.txt  
  inflating: lib/configuration/commons-collections-3.2.1.jar  
  inflating: lib/configuration/commons-configuration-1.6.jar  
  inflating: lib/configuration/commons-lang-2.6.jar  
  inflating: lib/configuration/commons-logging-1.1.1.jar  
  inflating: lib/guava/COPYING       
  inflating: lib/guava/guava-r08.jar  
  inflating: lib/javailp/javailp-1.2a.jar  
  inflating: lib/javaproj/javaproj-1.0.6.jar  
  inflating: lib/jewelcli/jewelcli-0.6.jar  
  inflating: lib/jogl/gluegen-rt-natives-linux-amd64.jar  
  inflating: lib/jogl/gluegen-rt-natives-linux-i586.jar  
  inflating: lib/jogl/gluegen-rt-natives-macosx-universal.jar  
  inflating: lib/jogl/gluegen-rt-natives-windows-amd64.jar  
  inflating: lib/jogl/gluegen-rt-natives-windows-i586.jar  
  inflating: lib/jogl/gluegen-rt.jar  
  inflating: lib/jogl/jogl-all-natives-linux-amd64.jar  
  inflating: lib/jogl/jogl-all-natives-linux-i586.jar  
  inflating: lib/jogl/jogl-all-natives-macosx-universal.jar  
  inflating: lib/jogl/jogl-all-natives-windows-amd64.jar  
  inflating: lib/jogl/jogl-all-natives-windows-i586.jar  
  inflating: lib/jogl/jogl-all.jar   
  inflating: lib/jogl/jogl.LICENSE.txt  
  inflating: lib/jts/LICENSE.txt     
  inflating: lib/jts/jts-1.11.jar    
  inflating: lib/lp_solve/LGPL       
  inflating: lib/lp_solve/README.html  
  inflating: lib/lp_solve/lpsolve55j.jar  
  inflating: lib/lp_solve/ux32/libbfp_GLPK.so  
  inflating: lib/lp_solve/ux32/libbfp_LUSOL.so  
  inflating: lib/lp_solve/ux32/libbfp_etaPFI.so  
  inflating: lib/lp_solve/ux32/liblpsolve55.a  
  inflating: lib/lp_solve/ux32/liblpsolve55.so  
  inflating: lib/lp_solve/ux32/liblpsolve55j.so  
  inflating: lib/lp_solve/ux32/libxli_CPLEX.so  
  inflating: lib/lp_solve/ux32/libxli_DIMACS.so  
  inflating: lib/lp_solve/ux32/libxli_LINDO.so  
  inflating: lib/lp_solve/ux32/libxli_MathProg.so  
  inflating: lib/lp_solve/ux32/libxli_XPRESS.so  
  inflating: lib/lp_solve/ux32/libxli_ZIMPL.so  
  inflating: lib/lp_solve/ux32/lp_solve  
  inflating: lib/lp_solve/ux64/libbfp_GLPK.so  
  inflating: lib/lp_solve/ux64/libbfp_LUSOL.so  
  inflating: lib/lp_solve/ux64/libbfp_etaPFI.so  
  inflating: lib/lp_solve/ux64/liblpsolve55.a  
  inflating: lib/lp_solve/ux64/liblpsolve55.so  
  inflating: lib/lp_solve/ux64/liblpsolve55j.so  
  inflating: lib/lp_solve/ux64/libxli_CPLEX.so  
  inflating: lib/lp_solve/ux64/libxli_DIMACS.so  
  inflating: lib/lp_solve/ux64/libxli_LINDO.so  
  inflating: lib/lp_solve/ux64/libxli_MathProg.so  
  inflating: lib/lp_solve/ux64/libxli_XPRESS.so  
  inflating: lib/lp_solve/ux64/lp_solve  
  inflating: lib/lp_solve/win32/lpsolve55j.dll  
  inflating: lib/lp_solve/win64/lpsolve55j.dll  
  inflating: lib/osmosis/commons-compress-1.2.jar  
  inflating: lib/osmosis/copying.txt  
  inflating: lib/osmosis/osmosis-core-0.41.jar  
  inflating: lib/osmosis/osmosis-pbf-0.41.jar  
  inflating: lib/osmosis/osmosis-xml-0.41.jar  
  inflating: lib/osmosis/osmpbf-1.1.1-754a33af.jar  
  inflating: lib/osmosis/protobuf-java-2.4.1.jar  
  inflating: lib/osmosis/xercesImpl-2.9.1.jar  
  inflating: lib/pngj/pngj-2.0.0.jar  
  inflating: lib/poly2tri/LICENSE.txt  
  inflating: lib/poly2tri/poly2tri-core-0.1.1-SNAPSHOT.jar  
  inflating: lib/slf4j/LICENSE.txt   
  inflating: lib/slf4j/slf4j-api-1.7.5.jar  
  inflating: lib/slf4j/slf4j-simple-1.7.5.jar  
  inflating: lib/trove/AUTHORS.txt   
  inflating: lib/trove/LICENSE.txt   
  inflating: lib/trove/README-license.txt  
  inflating: lib/trove/README.txt    
  inflating: lib/trove/trove-111118193120.jar  
  inflating: lib/trove/trove-3.0.1-src.jar  
  inflating: osm2world-windows.bat   
  inflating: resources/osm2world_definitions.inc  
  inflating: resources/shaders/background.fragment  
  inflating: resources/shaders/background.vertex  
  inflating: resources/shaders/default.fragment  
  inflating: resources/shaders/default.vertex  
  inflating: resources/shaders/nonarea.fragment  
  inflating: resources/shaders/nonarea.vertex  
  inflating: resources/shaders/shadowmap.fragment  
  inflating: resources/shaders/shadowmap.vertex  
  inflating: resources/shaders/shadowvolume.fragment  
  inflating: resources/shaders/shadowvolume.vertex  
koppi@x220:~/Downloads/OSM2World$ ls
augsburg-koenigsplatz-jsom.osm  example_config.properties     OSM2World-latest-bin.zip
augsburg-koenigsplatz.obj       gpl.txt                       OSM2World POVRay Includes 2011-11-09.zip
augsburg-koenigsplatz.obj.mtl   lgpl.txt                      osm2world.sh
augsburg-koenigsplatz.osm       lib                           OSM2World Texture Selection 2014-07-19.zip
augsburg-koenigsplatz.pov       muenchen.osm                  osm2world-windows.bat
augsburg-koenigsplatz.stl       OSM2World.jar                 resources
COPYING.txt                     OSM2World-latest-bin (1).zip  texture_config.properties
koppi@x220:~/Downloads/OSM2World$ unzip OSM2World\ Texture\ Selection\ 2014-07-19.zip 
Archive:  OSM2World Texture Selection 2014-07-19.zip
   creating: textures/
 extracting: textures/road_marking_crossing.png  
  inflating: textures/road_arrow_through_right.png  
  inflating: textures/road_arrow_through.png  
  inflating: textures/road_arrow_right_left.png  
  inflating: textures/road_arrow_right.png  
  inflating: textures/SolarPanel.jpg  
 extracting: textures/road_marking_dash.png  
  inflating: textures/powertower_horizontal.png  
 extracting: textures/powertower_horizontal.orig.png  
 extracting: textures/window_32.png  
 extracting: textures/window_16.png  
  inflating: textures/white.jpg      
  inflating: textures/Skybox_tut13.png  
  inflating: textures/README         
  inflating: textures/P1140080E_Water.jpg  
  inflating: textures/OSM2World_Domposter.png  
  inflating: textures/my_sand.jpg    
  inflating: textures/MarekTile0006_grey.jpg  
  inflating: textures/MarekTile0006.jpg  
  inflating: textures/MarekTile0004.jpg  
  inflating: textures/MarekTile0003.jpg  
  inflating: textures/MarekSeamlessBrick003.jpg  
  inflating: textures/MarekGrassDehydrated0001.jpg  
  inflating: textures/MarekGrasMoos0001_background.png  
  inflating: textures/MarekGrasMoos0001.jpg  
  inflating: textures/MarekFootway0005.jpg  
  inflating: textures/MarekFootway0004.jpg  
  inflating: textures/MarekFootway0003.jpg  
  inflating: textures/MarekConcrete0001.jpg  
  inflating: textures/MarekCompositeWall00001_transparent.png  
  inflating: textures/MarekCobblestone0003.jpg  
  inflating: textures/MarekAsphalt0001.jpg  
  inflating: textures/KnerrKerb0001.png  
  inflating: textures/KnerrGlassWall0001.jpg  
  inflating: textures/Grass-2048.JPG  
  inflating: textures/Fabi2-putz1.png  
  inflating: textures/DE_21_C6_Kies0001.jpg  
  inflating: textures/DE20F1GarageDoor00001_multitexture.png  
  inflating: textures/DE20E1_Fence0001_trans.png  
  inflating: textures/DE20E1_Fence0001.jpg  
  inflating: textures/DE20D4_OldCopper0001.jpg  
  inflating: textures/DE20B5outsideWoodWall0001.jpg  
  inflating: textures/DE19F1FreisingDoor00005_box_small.png  
  inflating: textures/arbaro_tree_coniferous.png  
  inflating: textures/arbaro_tree_broad_leaved_alphatest.png  
  inflating: textures/arbaro_tree_broad_leaved.png  
  inflating: textures/apfelbaum_alpha.png  
replace texture_config.properties? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: texture_config.properties  
koppi@x220:~/Downloads/OSM2World$ vi texture_config.properties 
koppi@x220:~/Downloads/OSM2World$ ./osm2world.sh -i muenchen.osm -o muenchen.pov
Poly2Tri exception for SurfaceArea(w0):
org.osm2world.core.util.exception.TriangulationException: java.lang.NullPointerException
    at org.osm2world.core.math.algorithms.Poly2TriTriangulationUtil.triangulateFast(Unknown Source)
    at org.osm2world.core.math.algorithms.Poly2TriTriangulationUtil.triangulate(Unknown Source)
    at org.osm2world.core.world.modules.SurfaceAreaModule$SurfaceArea.getTriangulationXZ(Unknown Source)
    at org.osm2world.core.world.data.AbstractAreaWorldObject.getEleConnectors(Unknown Source)
    at org.osm2world.core.world.data.AbstractAreaWorldObject.getEleConnectors(Unknown Source)
    at org.osm2world.core.ConversionFacade$1.perform(Unknown Source)
    at org.osm2world.core.ConversionFacade$1.perform(Unknown Source)
    at org.osm2world.core.util.FaultTolerantIterationUtil.iterate(Unknown Source)
    at org.osm2world.core.ConversionFacade.calculateElevations(Unknown Source)
    at org.osm2world.core.ConversionFacade.createRepresentations(Unknown Source)
    at org.osm2world.core.ConversionFacade.createRepresentations(Unknown Source)
    at org.osm2world.console.Output.output(Unknown Source)
    at org.osm2world.console.OSM2World.executeArgumentsGroup(Unknown Source)
    at org.osm2world.console.OSM2World.main(Unknown Source)
Caused by: java.lang.NullPointerException
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.isEdgeSideOfTriangle(DTSweep.java:543)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:567)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:604)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:626)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:583)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:348)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.sweep(DTSweep.java:110)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.triangulate(DTSweep.java:72)
    at org.poly2tri.Poly2Tri.triangulate(Poly2Tri.java:108)
    at org.poly2tri.Poly2Tri.triangulate(Poly2Tri.java:98)
    at org.poly2tri.Poly2Tri.triangulate(Poly2Tri.java:67)
    ... 14 more
... falling back to JTS triangulation.
Poly2Tri exception for SurfaceArea(w0):
org.osm2world.core.util.exception.TriangulationException: java.lang.NullPointerException
    at org.osm2world.core.math.algorithms.Poly2TriTriangulationUtil.triangulateFast(Unknown Source)
    at org.osm2world.core.math.algorithms.Poly2TriTriangulationUtil.triangulate(Unknown Source)
    at org.osm2world.core.world.modules.SurfaceAreaModule$SurfaceArea.getTriangulationXZ(Unknown Source)
    at org.osm2world.core.world.data.AbstractAreaWorldObject.getEleConnectors(Unknown Source)
    at org.osm2world.core.world.data.AbstractAreaWorldObject.getEleConnectors(Unknown Source)
    at org.osm2world.core.ConversionFacade$1.perform(Unknown Source)
    at org.osm2world.core.ConversionFacade$1.perform(Unknown Source)
    at org.osm2world.core.util.FaultTolerantIterationUtil.iterate(Unknown Source)
    at org.osm2world.core.ConversionFacade.calculateElevations(Unknown Source)
    at org.osm2world.core.ConversionFacade.createRepresentations(Unknown Source)
    at org.osm2world.core.ConversionFacade.createRepresentations(Unknown Source)
    at org.osm2world.console.Output.output(Unknown Source)
    at org.osm2world.console.OSM2World.executeArgumentsGroup(Unknown Source)
    at org.osm2world.console.OSM2World.main(Unknown Source)
Caused by: java.lang.NullPointerException
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.isEdgeSideOfTriangle(DTSweep.java:543)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:567)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:604)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:626)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:583)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:348)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.sweep(DTSweep.java:110)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.triangulate(DTSweep.java:72)
    at org.poly2tri.Poly2Tri.triangulate(Poly2Tri.java:108)
    at org.poly2tri.Poly2Tri.triangulate(Poly2Tri.java:98)
    at org.poly2tri.Poly2Tri.triangulate(Poly2Tri.java:67)
    ... 14 more
... falling back to JTS triangulation.
Poly2Tri exception for SurfaceArea(w0):
org.osm2world.core.util.exception.TriangulationException: java.lang.NullPointerException
    at org.osm2world.core.math.algorithms.Poly2TriTriangulationUtil.triangulateFast(Unknown Source)
    at org.osm2world.core.math.algorithms.Poly2TriTriangulationUtil.triangulate(Unknown Source)
    at org.osm2world.core.world.modules.SurfaceAreaModule$SurfaceArea.getTriangulationXZ(Unknown Source)
    at org.osm2world.core.world.data.AbstractAreaWorldObject.getEleConnectors(Unknown Source)
    at org.osm2world.core.world.data.AbstractAreaWorldObject.getEleConnectors(Unknown Source)
    at org.osm2world.core.ConversionFacade$1.perform(Unknown Source)
    at org.osm2world.core.ConversionFacade$1.perform(Unknown Source)
    at org.osm2world.core.util.FaultTolerantIterationUtil.iterate(Unknown Source)
    at org.osm2world.core.ConversionFacade.calculateElevations(Unknown Source)
    at org.osm2world.core.ConversionFacade.createRepresentations(Unknown Source)
    at org.osm2world.core.ConversionFacade.createRepresentations(Unknown Source)
    at org.osm2world.console.Output.output(Unknown Source)
    at org.osm2world.console.OSM2World.executeArgumentsGroup(Unknown Source)
    at org.osm2world.console.OSM2World.main(Unknown Source)
Caused by: java.lang.NullPointerException
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.isEdgeSideOfTriangle(DTSweep.java:543)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:567)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:583)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:583)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.edgeEvent(DTSweep.java:348)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.sweep(DTSweep.java:110)
    at org.poly2tri.triangulation.delaunay.sweep.DTSweep.triangulate(DTSweep.java:72)
    at org.poly2tri.Poly2Tri.triangulate(Poly2Tri.java:108)
    at org.poly2tri.Poly2Tri.triangulate(Poly2Tri.java:98)
    at org.poly2tri.Poly2Tri.triangulate(Poly2Tri.java:67)
    ... 14 more
... falling back to JTS triangulation.
time terrain interpolation: 0:00:01.118
time add constraints: 0:00:00.000
time enforce constraints: 0:00:00.000
koppi@x220:~/Downloads/OSM2World$ ls -alrt
total 115832
drwxrwxr-x  2 koppi koppi    12288 Jun 19  2014 textures
-rw-r--r--  1 koppi koppi     9398 Jun 19  2014 texture_config.properties
-rw-r--r--  1 koppi koppi       34 Apr 13 15:00 osm2world-windows.bat
-rwxr-xr-x  1 koppi koppi      624 Apr 13 15:00 osm2world.sh
-rw-r--r--  1 koppi koppi   730857 Apr 13 15:00 OSM2World.jar
drwxr-xr-x 16 koppi koppi     4096 Apr 13 15:00 lib
-rw-r--r--  1 koppi koppi     7651 Apr 13 15:00 lgpl.txt
-rw-r--r--  1 koppi koppi    35147 Apr 13 15:00 gpl.txt
-rw-r--r--  1 koppi koppi     1995 Apr 13 15:00 example_config.properties
-rw-r--r--  1 koppi koppi      787 Apr 13 15:00 COPYING.txt
-rw-rw-r--  1 koppi koppi 19710940 Apr 13 15:46 OSM2World-latest-bin.zip
-rw-rw-r--  1 koppi koppi 33123393 Apr 27 23:46 OSM2World POVRay Includes 2011-11-09.zip
-rw-rw-r--  1 koppi koppi 19710840 Apr 27 23:46 OSM2World-latest-bin (1).zip
-rw-rw-r--  1 koppi koppi 10207948 Apr 27 23:46 OSM2World Texture Selection 2014-07-19.zip
drwxr-xr-x 12 koppi koppi    81920 Apr 27 23:47 ..
-rw-rw-r--  1 koppi koppi        0 Apr 27 23:54 augsburg-koenigsplatz.osm
-rw-rw-r--  1 koppi koppi  1758192 Apr 27 23:54 augsburg-koenigsplatz-jsom.osm
-rw-rw-r--  1 koppi koppi  8090337 Apr 27 23:55 augsburg-koenigsplatz.pov
-rw-rw-r--  1 koppi koppi  2696708 Apr 27 23:57 muenchen.osm
-rw-rw-r--  1 koppi koppi     6525 Apr 27 23:58 augsburg-koenigsplatz.obj.mtl
-rw-rw-r--  1 koppi koppi  3541587 Apr 27 23:58 augsburg-koenigsplatz.obj
-rw-rw-r--  1 koppi koppi 10628905 Apr 28 00:01 augsburg-koenigsplatz.stl
drwxr-xr-x  3 koppi koppi     4096 Apr 28 00:15 resources
drwxrwxr-x  5 koppi koppi     4096 Apr 28 00:16 .
-rw-rw-r--  1 koppi koppi  8011620 Apr 28 00:16 muenchen.pov
koppi@x220:~/Downloads/OSM2World$ povray +d muenchen.pov 
Persistence of Vision(tm) Ray Tracer Version 3.7.1-alpha.8509766.unofficial (g++
 5.3.1 @ x86_64-pc-linux-gnu)
This is an unofficial version compiled by:
 Jakob Flierl <jakob.flierl@gmail.com>
 The POV-Ray Team is not responsible for supporting this version.

POV-Ray is based on DKBTrace 2.12 by David K. Buck & Aaron A. Collins
Copyright 1991-2016 Persistence of Vision Raytracer Pty. Ltd.

Primary POV-Ray 3.7 Architects/Developers: (Alphabetically)
  Chris Cason         Thorsten Froehlich  Christoph Lipka   

With Assistance From: (Alphabetically)
  Nicolas Calimet     Jerome Grimbert     James Holsenback    Christoph Hormann 
  Nathan Kopp         Juha Nieminen     

Past Contributors: (Alphabetically)
  Steve Anger         Eric Barish         Dieter Bayer        David K. Buck     
  Nicolas Calimet     Chris Cason         Aaron A. Collins    Chris Dailey      
  Steve Demlow        Andreas Dilger      Alexander Enzmann   Dan Farmer        
  Thorsten Froehlich  Mark Gordon         James Holsenback    Christoph Hormann 
  Mike Hough          Chris Huff          Kari Kivisalo       Nathan Kopp       
  Lutz Kretzschmar    Christoph Lipka     Jochen Lippert      Pascal Massimino  
  Jim McElhiney       Douglas Muir        Juha Nieminen       Ron Parker        
  Bill Pulver         Eduard Schwan       Wlodzimierz Skiba   Robert Skinner    
  Yvo Smellenbergh    Zsolt Szalavari     Scott Taylor        Massimo Valentini 
  Timothy Wegner      Drew Wells          Chris Young       

Other contributors are listed in the documentation.

Support libraries used by POV-Ray:
  ZLib 1.2.8, Copyright 1995-2012 Jean-loup Gailly and Mark Adler
  LibPNG 1.2.54, Copyright 1998-2012 Glenn Randers-Pehrson
  LibJPEG 80, Copyright 1991-2013 Thomas G. Lane, Guido Vollbeding
  LibTIFF 4.0.6, Copyright 1988-1997 Sam Leffler, 1991-1997 SGI
  Boost 1.58, http://www.boost.org/
  OpenEXR 2.2.0 and IlmBase 2.2.0, Copyright (c) 2002-2011 Industrial Light &
 Magic.

Parser Options
  Input file: muenchen.pov
  Remove bounds........On 
  Split unions.........Off
  Library paths:
    /opt/povray-3.7.0.RC7/share/povray-3.7
    /opt/povray-3.7.0.RC7/share/povray-3.7/ini
    /opt/povray-3.7.0.RC7/share/povray-3.7/include
    /opt/povray-3.7.0.rc7/share/povray-3.7
    /opt/povray-3.7.0.rc7/share/povray-3.7/ini
    /opt/povray-3.7.0.rc7/share/povray-3.7/include
    /usr/local/share/povray-3.7
    /usr/local/share/povray-3.7/ini
    /usr/local/share/povray-3.7/include
    /home/koppi/.fonts
    /home/koppi/.povray/local/inc/lgeo/lg
    /home/koppi/.povray/local/inc/lgeo/ar
    /home/koppi/.povray/local/stl
    /home/koppi/.povray/local/ebay
    /home/koppi/.povray/local/LightsysIV
    /home/koppi/.povray/local/citroen_gs
    /home/koppi/.povray/local/studio-lighting-3.7
    /home/koppi/.povray/local/hdr
    /home/koppi/.povray/local/iso_csg7
    /home/koppi/.povray/local/inc
    /home/koppi/.povray/local/inc/pov_objects1
    /home/koppi/.povray/local/inc/misc
    /home/koppi/.povray/local/inc/tomtree
  Clock value:    0.000  (Animation off)
Image Output Options
  Image resolution.....1024 by 768 (rows 1 to 768, columns 1 to 1024).
  Output file..........muenchen.png, 24 bpp PNG
  Dithering............Off
  Graphic display......On  (gamma: sRGB)
  Mosaic preview.......Off
  Continued trace......Off
Information Output Options
  All Streams to console..........On 
  Debug Stream to console.........On 
  Fatal Stream to console.........On 
  Render Stream to console........On 
  Statistics Stream to console....On 
  Warning Stream to console.......On 
==== [Parsing...] ==========================================================
File 'muenchen.pov' line 817: Possible Parse Error: Cannot find file
 './textures/powertower_vertical.orig.png', even after trying to append file
 type extension.
File 'muenchen.pov' line 817: Possible Parse Error: Cannot find image file.
Fatal error in parser: Cannot open file.
Render failed
```

**Comment by pinglis** [comment]
I've not used povray before but Blender has a similar problem with the
obj's created with OSM2World. Basically, it doesn't like to have a path in
.mtl file.

My workflow is therefore to do the following:

1. Use OSM2World to generate the obj and corresponding mtl file
2. Edit the mtl file and remove every instance of './textures/' so that
'./textures/powertower_vertical.orig.png' becomes
'powertower_vertical.orig.png'.
3. Copy obj and mtl into another directory where i have a copy of the
material files at the same level.
4. Run blender.

Try doing the same for POV and see if that works for you.

Ideally, what i think OSM2World should do is create obj and mtl files (and
i guess pov files) without paths for the materials and copy from the
./textures directory all textures it used into the same directory that it
creates it's output file.

paul

**Comment by koppi** [comment]
The file ```textures/powertower_vertical.orig.png'``` is indeed missing in my installation, see:
```bash
koppi@x220:~/Downloads/OSM2World/textures$ ls
apfelbaum_alpha.png                     MarekCobblestone0003.jpg                 P1140080E_Water.jpg
arbaro_tree_broad_leaved_alphatest.png  MarekCompositeWall00001_transparent.png  powertower_horizontal.orig.png
arbaro_tree_broad_leaved.png            MarekConcrete0001.jpg                    powertower_horizontal.png
arbaro_tree_coniferous.png              MarekFootway0003.jpg                     README
DE19F1FreisingDoor00005_box_small.png   MarekFootway0004.jpg                     road_arrow_right_left.png
DE20B5outsideWoodWall0001.jpg           MarekFootway0005.jpg                     road_arrow_right.png
DE20D4_OldCopper0001.jpg                MarekGrasMoos0001_background.png         road_arrow_through.png
DE20E1_Fence0001.jpg                    MarekGrasMoos0001.jpg                    road_arrow_through_right.png
DE20E1_Fence0001_trans.png              MarekGrassDehydrated0001.jpg             road_marking_crossing.png
DE20F1GarageDoor00001_multitexture.png  MarekSeamlessBrick003.jpg                road_marking_dash.png
DE_21_C6_Kies0001.jpg                   MarekTile0003.jpg                        Skybox_tut13.png
Fabi2-putz1.png                         MarekTile0004.jpg                        SolarPanel.jpg
Grass-2048.JPG                          MarekTile0006_grey.jpg                   white.jpg
KnerrGlassWall0001.jpg                  MarekTile0006.jpg                        window_16.png
KnerrKerb0001.png                       my_sand.jpg                              window_32.png
MarekAsphalt0001.jpg                    OSM2World_Domposter.png
```
I quickly copied owertower_horizontal.orig.png to powertower_vertical.orig.png as a workaraound: 
```bash
koppi@x220:~/Downloads/OSM2World/textures$ cp powertower_horizontal.orig.png powertower_vertical.orig.png
koppi@x220:~/Downloads/OSM2World/textures$ cd ..
koppi@x220:~/Downloads/OSM2World$ povray +d muenchen.pov 
```
Now POV-Ray runs and displays something. Where to get the file ```powertower_vertical.orig.png```?

**Comment by pinglis** [comment]
Probably the easiest thing to do then is to edit your
texture_config.properties file and remove the section that references that
file.

OSM2World should then resort to using its default values for powertowers
and won't try and apply textures that it doesn't have and the error will go
away.

paul

**Comment by koppi** [comment]
It would be the best solution to include the powertower_vertical.orig.png file in the file http://osm2world.org/download/files/misc/OSM2World%20Texture%20Selection%202014-07-19.zip
 at http://osm2world.org/download/ to get the best "first time OSM2World user" experience.

**Comment by tordanik** [comment]
The missing texture for power towers has since been added to the texture selection offered for download on http://osm2world.org/download/
