### ISSUE TITLE
Issue with invalid geometry

### ISSUE THREAD

**Issue by marius851000** [tordanik/OSM2World#178]
Sometimes, I have issue with invalid geometry. The strange part is that this happen with what seems to be normal osm data (first appeared with custom fictional map, then on real map export from osm here : https://www.openstreetmap.org/export#map=17/48.81738/2.31538 )

test exemple file, containing a single building that seems to be normal : https://marius851000-drive.mycozy.cloud/public?sharecode=VAsu4JSQQLWE

Deleting part of the building seems to solve the issue

Additionally, here is the log when trying to import the real data from the above link :

```org.osm2world.core.math.InvalidGeometryException: polygon must not be self-intersecting
Polygon vertices: [(-1002.368,-237.626), (-1023.141,-237.63), (-931.127,-237.627), (-951.888,-237.631), (-1002.368,-237.626)]
        at org.osm2world.core.math.SimplePolygonXZ.assertNotSelfIntersecting(SimplePolygonXZ.java:649)
        at org.osm2world.core.math.SimplePolygonXZ.<init>(SimplePolygonXZ.java:46)
        at org.osm2world.core.math.SimplePolygonXZ.getSimplifiedPolygon(SimplePolygonXZ.java:363)
        at org.osm2world.core.world.modules.building.BuildingPart.splitIntoWalls(BuildingPart.java:359)
        at org.osm2world.core.world.modules.building.BuildingPart.createComponents(BuildingPart.java:177)
        at org.osm2world.core.world.modules.building.BuildingPart.getAttachmentSurfaces(BuildingPart.java:481)
        at org.osm2world.core.world.modules.building.Building.getAttachmentSurfaces(Building.java:183)
        at org.osm2world.core.ConversionFacade.attachConnectors(ConversionFacade.java:324)
        at org.osm2world.core.ConversionFacade.createRepresentations(ConversionFacade.java:297)
        at org.osm2world.viewer.model.Data.loadOSMData(Data.java:65)
        at org.osm2world.viewer.control.actions.AbstractLoadOSMAction$LoadOSMThread.run(AbstractLoadOSMAction.java:84)```

**Comment by tordanik** [comment]
Thank you for the excellent bug report, your example file has made it easy for to 
understand and resolve this problem!

The cause of the error was OSM2World's overly aggressive attempt to simplify the building polygon. Because of the carefully mapped curves in the building's outline, the angle at each node is almost straight, so the code mistook those nodes as unnecesary nodes in a straight way and filtered them out. Naturally, the end result was a broken polygon.

I've fixed the problem in 88cda1e.
