### ISSUE TITLE
Using gui and windows batch to convert *.osm to *.obj produce non-identical results

### ISSUE THREAD

**Issue by acyiobs** [tordanik/OSM2World#206]
Hello, I am new to this useful package, and thank you to all contributors.
I am running a simple test to convert an *.osm file to an *.obj file.
The *.osm file is downloaded from https://api.openstreetmap.org/api/0.6/map?bbox=-111.93264,33.41965,-111.92882,33.42182

When using GUI, I  run .\osm2world-windows.bat --input gwc.osm --gui .  And save the file using File->Export obj file.
When using the windows batch (in cmd), I run .\osm2world-windows.bat --input gwc.osm --output gwc.obj

The above two methods do not produce identical output *.obj.
The GUI result looks good. The windows batch outputs the following exceptions.

Any help is appreciated!
--------------------------------   cmd output   ----------------------------------------------------------------
time terrain interpolation: 0:00:00.371
time add constraints: 0:00:00.000
time enforce constraints: 0:00:00.000
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.world.modules.RoadModule$RoadJunction.renderTo(RoadModule.java:569)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
n5264800429
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.target.common.AbstractTarget.drawTriangleStrip(AbstractTarget.java:145)
        at org.osm2world.core.world.modules.RoadModule$RoadCrossingAtConnector.renderTo(RoadModule.java:697)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
n3101278935
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.world.modules.RoadModule$RoadJunction.renderTo(RoadModule.java:569)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
n5264800268
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.target.common.AbstractTarget.drawTriangleStrip(AbstractTarget.java:145)
        at org.osm2world.core.world.modules.RoadModule$FlatTexturedLane.render(RoadModule.java:1919)
        at org.osm2world.core.world.modules.RoadModule$LaneConnection.renderTo(RoadModule.java:1832)
        at org.osm2world.core.world.modules.RoadModule$RoadConnector.renderTo(RoadModule.java:627)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
n3101278945
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.target.common.AbstractTarget.drawTriangleStrip(AbstractTarget.java:145)
        at org.osm2world.core.world.modules.RoadModule$RoadCrossingAtConnector.renderTo(RoadModule.java:697)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
n2822050831
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.target.common.AbstractTarget.drawTriangleStrip(AbstractTarget.java:145)
        at org.osm2world.core.world.modules.RoadModule$FlatTexturedLane.render(RoadModule.java:1919)
        at org.osm2world.core.world.modules.RoadModule$LaneConnection.renderTo(RoadModule.java:1832)
        at org.osm2world.core.world.modules.RoadModule$RoadConnector.renderTo(RoadModule.java:627)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
n5201685468
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.target.common.AbstractTarget.drawTriangleStrip(AbstractTarget.java:145)
        at org.osm2world.core.world.modules.RoadModule$FlatTexturedLane.render(RoadModule.java:1919)
        at org.osm2world.core.world.modules.RoadModule$Lane.renderTo(RoadModule.java:1775)
        at org.osm2world.core.world.modules.RoadModule$Road.renderLanesTo(RoadModule.java:1460)
        at org.osm2world.core.world.modules.RoadModule$Road.renderTo(RoadModule.java:1498)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
n5343247777->n5343247778
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.target.common.AbstractTarget.drawTriangleStrip(AbstractTarget.java:145)
        at org.osm2world.core.world.modules.RoadModule$FlatTexturedLane.render(RoadModule.java:1919)
        at org.osm2world.core.world.modules.RoadModule$Lane.renderTo(RoadModule.java:1775)
        at org.osm2world.core.world.modules.RoadModule$Road.renderLanesTo(RoadModule.java:1460)
        at org.osm2world.core.world.modules.RoadModule$Road.renderTo(RoadModule.java:1498)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
n3101278945->n3101278939
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.target.common.AbstractTarget.drawTriangleStrip(AbstractTarget.java:145)
        at org.osm2world.core.world.modules.RoadModule$FlatTexturedLane.render(RoadModule.java:1919)
        at org.osm2world.core.world.modules.RoadModule$Lane.renderTo(RoadModule.java:1775)
        at org.osm2world.core.world.modules.RoadModule$Road.renderLanesTo(RoadModule.java:1460)
        at org.osm2world.core.world.modules.RoadModule$Road.renderTo(RoadModule.java:1498)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
n41714341->n2822050831
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.target.Target.drawTriangles(Target.java:52)
        at org.osm2world.core.target.Target.drawMesh(Target.java:165)
        at org.osm2world.core.target.common.model.Model.lambda$render$0(Model.java:35)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
        at org.osm2world.core.target.common.model.Model.render(Model.java:35)
        at org.osm2world.core.target.common.model.Model.render(Model.java:30)
        at org.osm2world.core.target.Target.drawModel(Target.java:160)
        at org.osm2world.core.world.modules.BicycleParkingModule$BicycleStands.renderTo(BicycleParkingModule.java:187)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
w553577591
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.world.modules.building.WallSurface.renderTo(WallSurface.java:265)
        at org.osm2world.core.world.modules.building.Wall.renderTo(Wall.java:305)
        at org.osm2world.core.world.modules.building.Wall.renderTo(Wall.java:88)
        at org.osm2world.core.world.modules.building.BuildingPart.lambda$renderTo$10(BuildingPart.java:458)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.osm2world.core.world.modules.building.BuildingPart.renderTo(BuildingPart.java:458)
        at org.osm2world.core.world.modules.building.Building.lambda$renderTo$4(Building.java:159)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:31)
        at org.osm2world.core.world.modules.building.Building.renderTo(Building.java:159)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
BuildingPart(w552636700)
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.world.modules.building.WallSurface.renderTo(WallSurface.java:265)
        at org.osm2world.core.world.modules.building.Wall.renderTo(Wall.java:305)
        at org.osm2world.core.world.modules.building.Wall.renderTo(Wall.java:88)
        at org.osm2world.core.world.modules.building.BuildingPart.lambda$renderTo$10(BuildingPart.java:458)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.osm2world.core.world.modules.building.BuildingPart.renderTo(BuildingPart.java:458)
        at org.osm2world.core.world.modules.building.Building.lambda$renderTo$4(Building.java:159)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:31)
        at org.osm2world.core.world.modules.building.Building.renderTo(Building.java:159)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
BuildingPart(w30407018)
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.target.common.AbstractTarget.drawTriangleStrip(AbstractTarget.java:145)
        at org.osm2world.core.world.modules.building.Door.renderTo(Door.java:79)
        at org.osm2world.core.world.modules.building.WallSurface.renderTo(WallSurface.java:177)
        at org.osm2world.core.world.modules.building.Wall.renderTo(Wall.java:305)
        at org.osm2world.core.world.modules.building.Wall.renderTo(Wall.java:88)
        at org.osm2world.core.world.modules.building.BuildingPart.lambda$renderTo$10(BuildingPart.java:458)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.osm2world.core.world.modules.building.BuildingPart.renderTo(BuildingPart.java:458)
        at org.osm2world.core.world.modules.building.Building.lambda$renderTo$4(Building.java:159)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:31)
        at org.osm2world.core.world.modules.building.Building.renderTo(Building.java:159)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
BuildingPart(w30406793)
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.world.modules.SurfaceAreaModule$SurfaceArea.renderTo(SurfaceAreaModule.java:121)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
w552258040
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.target.common.AbstractTarget.drawTriangleStrip(AbstractTarget.java:145)
        at org.osm2world.core.world.modules.PowerModule$PhotovoltaicPlant.renderPanelsTo(PowerModule.java:969)
        at org.osm2world.core.world.modules.PowerModule$PhotovoltaicPlant.renderTo(PowerModule.java:922)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
w909817898
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.world.modules.building.roof.HeightfieldRoof.renderTo(HeightfieldRoof.java:165)
        at org.osm2world.core.world.modules.building.BuildingPart.renderTo(BuildingPart.java:462)
        at org.osm2world.core.world.modules.building.Building.lambda$renderTo$4(Building.java:159)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:31)
        at org.osm2world.core.world.modules.building.Building.renderTo(Building.java:159)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
BuildingPart(w29216331)
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.target.common.AbstractTarget.drawTriangleStrip(AbstractTarget.java:145)
        at org.osm2world.core.world.modules.PowerModule$PhotovoltaicPlant.renderPanelsTo(PowerModule.java:977)
        at org.osm2world.core.world.modules.PowerModule$PhotovoltaicPlant.renderTo(PowerModule.java:922)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
w909817894
ignored exception:
java.lang.NullPointerException: Cannot invoke "java.io.File.toURI()" because "this.objDirectory" is null
        at org.osm2world.core.target.obj.ObjTarget.textureToPath(ObjTarget.java:239)
        at org.osm2world.core.target.obj.ObjTarget.writeMaterial(ObjTarget.java:316)
        at org.osm2world.core.target.obj.ObjTarget.useMaterial(ObjTarget.java:154)
        at org.osm2world.core.target.obj.ObjTarget.drawFace(ObjTarget.java:131)
        at org.osm2world.core.target.common.FaceTarget.drawTriangles(FaceTarget.java:259)
        at org.osm2world.core.world.modules.SurfaceAreaModule$SurfaceArea.renderTo(SurfaceAreaModule.java:121)
        at org.osm2world.core.target.TargetUtil.renderObject(TargetUtil.java:82)
        at org.osm2world.core.target.TargetUtil.lambda$renderWorldObjects$0(TargetUtil.java:33)
        at org.osm2world.core.util.FaultTolerantIterationUtil.forEach(FaultTolerantIterationUtil.java:19)
        at org.osm2world.core.target.TargetUtil.renderWorldObjects(TargetUtil.java:30)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(ObjWriter.java:63)
        at org.osm2world.console.Output.output(Output.java:178)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:210)
        at org.osm2world.console.OSM2World.main(OSM2World.java:144)
this exception occurred for the following input:
w-1

**Comment by tordanik** [comment]
Good catch, this appears to have affected specifically OBJ output files in the current directory which were specified with just the filename (e.g. `myfile.obj` rather than `/path/to/myfile.obj`). The code for accessing the parent directory did not handle this case correctly, and was therefore not able to place the textures in that directory. I've fixed this in e1c84eb, the change will be part of the next build.
