### ISSUE TITLE
Command line: missing camera/projection causes NPE

### ISSUE THREAD

**Issue by tordanik** [tordanik/OSM2World#69]
Entirely omitting camera information with PNG output causes a NullPointerException:

```
Exception in thread "main" java.lang.NullPointerException
        at org.osm2world.core.target.jogl.JOGLTarget.applyProjectionMatricesForPart(JOGLTarget.java:320)
        at org.osm2world.core.target.jogl.JOGLTarget.renderPart(JOGLTarget.java:245)
        at org.osm2world.console.ImageExporter.writeImageFile(ImageExporter.java:250)
        at org.osm2world.console.Output.output(Output.java:159)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(OSM2World.java:199)
        at org.osm2world.console.OSM2World.main(OSM2World.java:130)
```

It would be preferable to fall back to the bounds in the data file and/or print a better warning.

**Comment by Lan5432** [comment]
Excuse me, but to better understand this. The problem is that ConversionFacade cf is not properly set up in lines 53-75 because no conditional branch is triggered? And then something breaks when calling a method in JOGLTarget?

Thanks in advance.

**Comment by tordanik** [comment]
The problem is actually in the section between the lines 84 and 134. The camera and projection variables are never set in some cases, which causes the NPE.

**Comment by tordanik** [comment]
This has been resolved. A simple OSM2World command such as `-i in.osm -o out.png` will now assume an orthographic view from the South.
